/*
 * Copyright 2026 Two Bear Capital
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.twobearcapital.bigquery.jdbc.base;

import com.twobearcapital.bigquery.jdbc.BQSQLFeatureNotSupportedException;
import java.sql.*;

/**
 * Base Connection implementation that provides default exception-throwing implementations
 * for all unsupported Connection methods.
 *
 * <p>Subclasses should override only the methods they actually support.</p>
 *
 * @since 1.0.0
 */
public abstract class AbstractBQConnection extends BaseCloseable implements Connection {

	// CallableStatement - not supported

	@Override
	public CallableStatement prepareCall(String sql) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("CallableStatement not supported by BigQuery");
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("CallableStatement not supported");
	}

	@Override
	public CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency,
			int resultSetHoldability) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("CallableStatement not supported");
	}

	// Savepoints - not supported

	@Override
	public Savepoint setSavepoint() throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Savepoints not supported");
	}

	@Override
	public Savepoint setSavepoint(String name) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Savepoints not supported");
	}

	@Override
	public void rollback(Savepoint savepoint) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Savepoints not supported");
	}

	@Override
	public void releaseSavepoint(Savepoint savepoint) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Savepoints not supported");
	}

	// Type maps - not supported

	@Override
	public void setTypeMap(java.util.Map<String, Class<?>> map) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Custom type maps not supported");
	}

	// Generated keys - not supported

	@Override
	public PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException {
		checkClosed();
		if (autoGeneratedKeys != Statement.NO_GENERATED_KEYS) {
			throw new BQSQLFeatureNotSupportedException("Generated keys not supported");
		}
		return prepareStatement(sql);
	}

	@Override
	public PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Generated keys not supported");
	}

	@Override
	public PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Generated keys not supported");
	}

	// LOB creation - not supported

	@Override
	public Clob createClob() throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Clob not supported");
	}

	@Override
	public Blob createBlob() throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Blob not supported");
	}

	@Override
	public NClob createNClob() throws SQLException {
		throw new BQSQLFeatureNotSupportedException("NClob not supported");
	}

	@Override
	public SQLXML createSQLXML() throws SQLException {
		throw new BQSQLFeatureNotSupportedException("SQLXML not supported");
	}

	@Override
	public Array createArrayOf(String typeName, Object[] elements) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("createArrayOf not supported");
	}

	@Override
	public Struct createStruct(String typeName, Object[] attributes) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("createStruct not supported");
	}

	// Sharding - not supported

	@Override
	public boolean setShardingKeyIfValid(ShardingKey shardingKey, ShardingKey superShardingKey, int timeout)
			throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Sharding not supported");
	}

	@Override
	public boolean setShardingKeyIfValid(ShardingKey shardingKey, int timeout) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Sharding not supported");
	}

	@Override
	public void setShardingKey(ShardingKey shardingKey, ShardingKey superShardingKey) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Sharding not supported");
	}

	@Override
	public void setShardingKey(ShardingKey shardingKey) throws SQLException {
		throw new BQSQLFeatureNotSupportedException("Sharding not supported");
	}
}
