/**
 * Sync the repository's Markdown docs into the Starlight content collection.
 *
 * The repo keeps its docs as plain GitHub-readable Markdown under ../docs (no
 * frontmatter). Starlight requires a `title` in frontmatter, so rather than
 * editing every doc, this script derives the title from the first H1 and writes
 * frontmatter'd copies into src/content/docs/guides/. The output dir is
 * gitignored — it is a build artifact, never edited by hand.
 *
 *   ../docs/*.md  ->  src/content/docs/guides/<slug>.md
 *
 * Generated reference tables (../docs/generated/*.md, produced by DocGen) are NOT
 * synced as separate pages. Instead a guide embeds one with an include marker:
 *
 *   <!-- @include: generated/connection-properties.md -->
 *
 * which is replaced here with the generated table's body (its DO-NOT-EDIT comment
 * and H1 stripped). On GitHub the marker is an invisible comment and the guide's
 * prose links to the generated file; on the site the table is inlined and any
 * `generated/*.md` links (which would 404) are unwrapped to plain text. This keeps
 * one page per topic on the site while preserving the generator's drift guarantee.
 *
 * Doc scoping convention: only TOP-LEVEL ../docs/*.md is user-facing and synced.
 * Contributor/build/release docs live in ../docs/contributing/ and are not synced.
 */
import {
	readdirSync,
	readFileSync,
	writeFileSync,
	mkdirSync,
	rmSync,
	existsSync,
} from 'node:fs';
import { join, resolve, extname } from 'node:path';
import { fileURLToPath } from 'node:url';

const scriptDir = fileURLToPath(new URL('.', import.meta.url));
const websiteDir = resolve(scriptDir, '..');
const repoRoot = resolve(websiteDir, '..');

const docsDir = join(repoRoot, 'docs');
const generatedDir = join(docsDir, 'generated');
const contentDir = join(websiteDir, 'src', 'content', 'docs');
const guidesOut = join(contentDir, 'guides');
const referenceOut = join(contentDir, 'reference'); // legacy; removed below

/** Turn a file name like CONNECTION_PROPERTIES.md into "connection-properties". */
function slugify(fileName) {
	return fileName
		.slice(0, fileName.length - extname(fileName).length)
		.toLowerCase()
		.replace(/[^a-z0-9]+/g, '-')
		.replace(/^-+|-+$/g, '');
}

/** Remove a leading HTML comment block (e.g. DocGen's DO-NOT-EDIT banner). */
function stripLeadingComment(md) {
	return md.replace(/^\s*<!--[\s\S]*?-->\s*/, '');
}

/** Strip the leading comment and the first H1, returning the remaining body. */
function bodyWithoutTitle(md) {
	const lines = stripLeadingComment(md).split('\n');
	for (let i = 0; i < lines.length; i++) {
		if (/^#\s+/.test(lines[i])) {
			lines.splice(i, 1);
			break;
		}
	}
	return lines.join('\n').replace(/^\n+/, '').trimEnd();
}

/** Load generated tables keyed by slug, each as a heading-less body for inlining. */
function loadGenerated() {
	const map = {};
	if (!existsSync(generatedDir)) {
		return map;
	}
	for (const entry of readdirSync(generatedDir, { withFileTypes: true })) {
		if (entry.isFile() && entry.name.endsWith('.md')) {
			map[slugify(entry.name)] = bodyWithoutTitle(readFileSync(join(generatedDir, entry.name), 'utf8'));
		}
	}
	return map;
}

const INCLUDE_RE = /^[ \t]*<!--\s*@include:\s*generated\/([a-z0-9-]+)\.md\s*-->[ \t]*$/gm;
const GENERATED_LINK_RE = /\[([^\]]+)\]\(generated\/[a-z0-9-]+\.md(?:#[^)]*)?\)/g;

/** Replace `<!-- @include: generated/<name>.md -->` markers with the generated body. */
function inlineIncludes(md, generated) {
	return md.replace(INCLUDE_RE, (_full, name) => {
		if (generated[name] == null) {
			console.warn(`[sync-docs] warning: @include target generated/${name}.md not found`);
			return '';
		}
		return generated[name];
	});
}

/** Unwrap links to generated/*.md to plain text (those pages don't exist on the site). */
function stripGeneratedLinks(md) {
	return md.replace(GENERATED_LINK_RE, '$1');
}

/**
 * Build the Starlight page: strip leading comment, pull the first H1 out to use
 * as the frontmatter title (avoiding a duplicate heading), prepend frontmatter.
 */
function toStarlightPage(md, fallbackTitle) {
	const lines = stripLeadingComment(md).split('\n');
	let title = fallbackTitle;
	for (let i = 0; i < lines.length; i++) {
		const match = lines[i].match(/^#\s+(.+?)\s*$/);
		if (match) {
			title = match[1];
			lines.splice(i, 1);
			break;
		}
	}
	const body = lines.join('\n').replace(/^\n+/, '');
	return `---\ntitle: ${JSON.stringify(title)}\n---\n\n${body}`;
}

function resetDir(dir) {
	rmSync(dir, { recursive: true, force: true });
	mkdirSync(dir, { recursive: true });
}

/**
 * The Javadoc API reference (public/api/) is generated by Maven during deploy
 * (see `npm run api` / the docs-site workflow). When it's absent — e.g. local
 * `npm run dev` — drop in a placeholder so the "Javadoc API" link doesn't 404.
 * Never overwrite a real Javadoc build.
 */
function ensureApiPlaceholder() {
	const apiDir = join(websiteDir, 'public', 'api');
	const indexFile = join(apiDir, 'index.html');
	if (existsSync(indexFile)) {
		return;
	}
	mkdirSync(apiDir, { recursive: true });
	writeFileSync(
		indexFile,
		`<!doctype html>
<meta charset="utf-8">
<title>API reference not built</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 40rem; margin: 4rem auto; padding: 0 1.5rem; line-height: 1.6; }
  code { background: #f0f0f0; padding: 0.1em 0.4em; border-radius: 3px; }
</style>
<h1>Javadoc API reference</h1>
<p>The API reference is generated from the source during deployment and isn't present in this local build.</p>
<p>To build it locally, run <code>npm run api</code> from the <code>website/</code> directory (requires a JDK), then reload.</p>
<p><a href="/">← Back to the docs</a></p>
`,
		'utf8',
	);
}

/** Sync the top-level guide docs, inlining generated tables and stripping their links. */
function syncGuides(generated) {
	const written = [];
	for (const entry of readdirSync(docsDir, { withFileTypes: true })) {
		if (!entry.isFile() || !entry.name.endsWith('.md')) {
			continue;
		}
		const slug = slugify(entry.name);
		let raw = readFileSync(join(docsDir, entry.name), 'utf8');
		raw = inlineIncludes(raw, generated);
		raw = stripGeneratedLinks(raw);
		writeFileSync(join(guidesOut, `${slug}.md`), toStarlightPage(raw, slug), 'utf8');
		written.push(slug);
	}
	return written;
}

resetDir(guidesOut);
rmSync(referenceOut, { recursive: true, force: true }); // remove any stale reference pages
const generated = loadGenerated();
const guides = syncGuides(generated);
ensureApiPlaceholder();

if (guides.length === 0) {
	console.warn(`[sync-docs] warning: no guide docs found in ${docsDir}`);
}
console.log(
	`[sync-docs] ${guides.length} guide(s); ${Object.keys(generated).length} generated table(s) available to inline`,
);
